plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/araya/Downloads/digital360-webv2/digital360-web/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]